### ISSUE TITLE
what's "model.safetensors" exactly?

### ISSUE THREAD

**Issue by Sylariam** [EmmanuelMr18/Comfyui-Transfer-Style-Workflow#1]
Hi, I'm trying to reproduce the workflow, but I can't find"model.safetensors" in CLIPVisionLoader. What is it and where can I find it? Thanks for the help

**Comment by EmmanuelMr18** [comment]
This is the clipVisionLoader 
![image](https://github.com/EmmanuelMr18/Comfyui-Transfer-Style-Workflow/assets/31712515/a56a2c91-7aa0-45da-9ce9-f32ab5424e82)
https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors

And here is the IPAdapter repository in case that you find it interesting. https://github.com/cubiq/ComfyUI_IPAdapter_plus

**Comment by Sylariam** [comment]
Much appreciated. Great work btw
